source 'https://rubygems.org'

gem 'rack'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'sprockets'
gem 'sprockets-sass'
gem 'sass'
gem 'compass'
gem 'cucumber'
gem 'capybara'
gem 'rspec'
gem 'selenium-webdriver'